@echo off
setlocal

set "ROOT=%~dp0"
set "PSCMD=$root = '%ROOT%';"
set "PSCMD=%PSCMD% function Clean-Text($text) {"
set "PSCMD=%PSCMD% $text = $text -replace '`([^`]+)`', '$1';"
set "PSCMD=%PSCMD% $text = $text -replace '\\*\\*([^*]+)\\*\\*', '$1';"
set "PSCMD=%PSCMD% $text = $text -replace '\\*([^*]+)\\*', '$1';"
set "PSCMD=%PSCMD% $text = $text -replace '\\[([^\\]]+)\\]\\([^\\)]+\\)', '$1';"
set "PSCMD=%PSCMD% $text = $text -replace '[_#>]', '';"
set "PSCMD=%PSCMD% return $text.Trim();"
set "PSCMD=%PSCMD% }"
set "PSCMD=%PSCMD% function Get-Title($path) {"
set "PSCMD=%PSCMD% $lines = Get-Content -Path $path -ErrorAction SilentlyContinue;"
set "PSCMD=%PSCMD% if (-not $lines) { return (Get-Item $path).BaseName -replace '[-_]', ' '; }"
set "PSCMD=%PSCMD% foreach ($line in $lines) {"
set "PSCMD=%PSCMD% $trimmed = $line.Trim();"
set "PSCMD=%PSCMD% if (-not $trimmed) { continue }"
set "PSCMD=%PSCMD% $match = [regex]::Match($trimmed, '^#{1,6}\\s+(.*)$');"
set "PSCMD=%PSCMD% if ($match.Success) { return (Clean-Text $match.Groups[1].Value) }"
set "PSCMD=%PSCMD% }"
set "PSCMD=%PSCMD% return (Get-Item $path).BaseName -replace '[-_]', ' ';"
set "PSCMD=%PSCMD% }"
set "PSCMD=%PSCMD% function Get-Excerpt($path, [int]$limit = 180) {"
set "PSCMD=%PSCMD% $text = Get-Content -Path $path -Raw -ErrorAction SilentlyContinue;"
set "PSCMD=%PSCMD% if (-not $text) { return '' }"
set "PSCMD=%PSCMD% $text = [regex]::Replace($text, '(?s)```.*?```', '');"
set "PSCMD=%PSCMD% $text = [regex]::Replace($text, '^#{1,6}.*$', '', 'Multiline');"
set "PSCMD=%PSCMD% $text = [regex]::Replace($text, '^>\\s?', '', 'Multiline');"
set "PSCMD=%PSCMD% $text = Clean-Text $text;"
set "PSCMD=%PSCMD% $text = [regex]::Replace($text, '\\s+', ' ');"
set "PSCMD=%PSCMD% if ($text.Length -gt $limit) { return $text.Substring(0, $limit - 3) + '...' }"
set "PSCMD=%PSCMD% return $text;"
set "PSCMD=%PSCMD% }"
set "PSCMD=%PSCMD% function Get-SearchText($path) {"
set "PSCMD=%PSCMD% $text = Get-Content -Path $path -Raw -ErrorAction SilentlyContinue;"
set "PSCMD=%PSCMD% if (-not $text) { return '' }"
set "PSCMD=%PSCMD% $text = [regex]::Replace($text, '(?s)```.*?```', '');"
set "PSCMD=%PSCMD% $text = [regex]::Replace($text, '^#{1,6}.*$', '', 'Multiline');"
set "PSCMD=%PSCMD% $text = [regex]::Replace($text, '^>\\s?', '', 'Multiline');"
set "PSCMD=%PSCMD% $text = Clean-Text $text;"
set "PSCMD=%PSCMD% $text = [regex]::Replace($text, '\\s+', ' ');"
set "PSCMD=%PSCMD% return $text;"
set "PSCMD=%PSCMD% }"
set "PSCMD=%PSCMD% $entries = @();"
set "PSCMD=%PSCMD% Get-ChildItem -Path $root -Recurse -File -Filter *.md | ForEach-Object {"
set "PSCMD=%PSCMD% $path = $_.FullName;"
set "PSCMD=%PSCMD% if ($path -match '\\\\.git\\\\' -or $path -match '\\\\node_modules\\\\' -or $path -match '\\\\vendor\\\\') { return }"
set "PSCMD=%PSCMD% $relative = $path.Substring($root.Length);"
set "PSCMD=%PSCMD% if ($relative.StartsWith('\\') -or $relative.StartsWith('/')) { $relative = $relative.Substring(1) }"
set "PSCMD=%PSCMD% $folder = [System.IO.Path]::GetDirectoryName($relative);"
set "PSCMD=%PSCMD% if ([string]::IsNullOrWhiteSpace($folder) -or $folder -eq '.') {"
set "PSCMD=%PSCMD% $folderLabel = 'Root';"
set "PSCMD=%PSCMD% $relativeWithin = $relative;"
set "PSCMD=%PSCMD% } else {"
set "PSCMD=%PSCMD% $folderLabel = $folder -replace '\\\\', '/';"
set "PSCMD=%PSCMD% $relativeWithin = $relative.Substring($folder.Length + 1) -replace '\\\\', '/';"
set "PSCMD=%PSCMD% }"
set "PSCMD=%PSCMD% $updated = [int][Math]::Floor((($_.LastWriteTimeUtc) - [datetime]'1970-01-01').TotalSeconds);"
set "PSCMD=%PSCMD% $entries += [ordered]@{"
set "PSCMD=%PSCMD% relative = $relative -replace '\\\\', '/';"
set "PSCMD=%PSCMD% title = Get-Title $path;"
set "PSCMD=%PSCMD% excerpt = Get-Excerpt $path;"
set "PSCMD=%PSCMD% search = Get-SearchText $path;"
set "PSCMD=%PSCMD% updated = $updated;"
set "PSCMD=%PSCMD% folder = $folderLabel;"
set "PSCMD=%PSCMD% relativeWithin = $relativeWithin;"
set "PSCMD=%PSCMD% }"
set "PSCMD=%PSCMD% }"
set "PSCMD=%PSCMD% $entries = $entries | Sort-Object -Property updated -Descending;"
set "PSCMD=%PSCMD% $payload = [ordered]@{ count = $entries.Count; entries = $entries };"
set "PSCMD=%PSCMD% $jsonPath = Join-Path $root 'lore-index.json';"
set "PSCMD=%PSCMD% $dataPath = Join-Path $root 'lore-index.data.js';"
set "PSCMD=%PSCMD% $json = $payload | ConvertTo-Json -Depth 6;"
set "PSCMD=%PSCMD% Set-Content -Path $jsonPath -Value $json -Encoding UTF8;"
set "PSCMD=%PSCMD% $js = 'window.LORE_ENTRIES = ' + $json + ';';"
set "PSCMD=%PSCMD% Set-Content -Path $dataPath -Value $js -Encoding UTF8;"

powershell -NoProfile -ExecutionPolicy Bypass -Command "%PSCMD%"

if errorlevel 1 (
  echo Failed to rebuild lore index.
  exit /b 1
)

echo Lore index updated.
exit /b 0
