window.LORE_ENTRIES = {
    "count":  7,
    "entries":  [
                    {
                        "relative":  "Basic Lore/Pirates, Bandits and Raiders.md",
                        "title":  "Pirates, Bandits and Raiders",
                        "excerpt":  "Pirates and bandits exist on the margins of human space, surviving in the gaps left by failing infrastructure, fading oversight, and the slow decay of interstellar connectivity....",
                        "search":  "Pirates and bandits exist on the margins of human space, surviving in the gaps left by failing infrastructure, fading oversight, and the slow decay of interstellar connectivity. Their structure ranges from single-ship operations with desperate crews to loosely organized factions flying under self-declared banners of independence-though most lack recognized territory and rarely hold captured colonies for long before they\u0027re dismantled by central authority. Their ships are as varied as their motives: repurposed industrial freighters, stolen civilian craft, gutted mining rigs retrofitted with weapon mounts, or even old military hulls held together by luck and stolen parts. Some strike out of desperation, others for profit, and a few under ideological pretense-anti-government, separatist, or anarchist. Most, however, simply want to survive, and their targets reflect that. They prey on the weak and the isolated: drifting vessels mid-corridor, colonies left out of rotation too long, outposts with minimal defenses. Functioning gates are rarely targeted, not out of mercy, but because disrupting a gate disrupts their own routes just as badly. Stolen cargo is either used, sold on black markets, or held for ransom. Fuel, food, and munitions are scrounged from ambushes or traded in shadowy backrooms of fringe colonies that look the other way. To the average colonist, pirates are a terrifying unknown. To experienced ship crews, theyâ€™re more of a wildcard-some encounters end in tense stand-offs, others in blood. Theyâ€™re not everywhere, but theyâ€™re common enough that no vessel travels without at least one mounted weapon and a crew ready to use it.",
                        "updated":  1766132632,
                        "folder":  "Basic Lore",
                        "relativeWithin":  "Pirates, Bandits and Raiders.md"
                    },
                    {
                        "relative":  "Basic Lore/Ships.md",
                        "title":  "Ships",
                        "excerpt":  "Interstellar ships form the backbone of humanityâ€™s crumbling infrastructure, ferrying people, supplies, and information between scattered Colonies via the unstable Corridors n...",
                        "search":  "Interstellar ships form the backbone of humanityâ€™s crumbling infrastructure, ferrying people, supplies, and information between scattered Colonies via the unstable Corridors network. Their crews are often the only thread connecting humanityâ€™s fractured outposts. Ship Types â€¢ Ships vary from small haulers and corvettes to large freighters and carrier-class transports, though all are built for function over form. â€¢ Civilian ships are modular, refitted constantly, and often patchwork relics of older designs. â€¢ Military, paramilitary, and corporate vessels also exist, though even these tend to be underpowered, overused, and stretched thin. Corridor Travel â€¢ Ships must enter and exit Corridors via Gates, which stabilize the journey and reduce the risk of catastrophic failure. â€¢ While in transit, ships are exposed to Corridor Radiation, requiring robust hull shielding and post-travel decontamination procedures. â€¢ Internal systems often suffer malfunctions during transit, crew intervention is mandatory for repairs, calibration, and maintaining life support. Crew Roles A typical crew is lean but skilled. Roles often include: â€¢ Navigator/Pilot â€“ Plots transit routes and handles gate alignments. â€¢ Mechanic/Engineer â€“ Maintains ship integrity, handles emergency repairs, and monitors life support. â€¢ Medical Officer â€“ Treats injuries and monitors radiation exposure. â€¢ Cargo/Systems Officer â€“ Manages supplies, ballast, and power distribution. â€¢ Captain/Commander â€“ Makes route decisions, enforces priorities, and often negotiates at each stop. Smaller ships may consolidate roles; larger ones may have redundancy or entire teams. Life Onboard â€¢ Life aboard ship is tense, exhausting, and dangerous. Crew members live in close quarters, share limited amenities, and face constant equipment degradation. â€¢ Crews often operate under tight contracts from colonial governments, Earth authorities, or corporate sponsors; but many run independent. â€¢ Salvage, courier runs, emergency resupply, or medical retrievals are common assignments. Not all of them are above-board. Reputation and Culture â€¢ Ship crews are respected and pitied in equal measure. Their work keeps the system functioning, but at significant personal cost. â€¢ Theyâ€™re often superstitious, especially about routes that have gone â€œdarkâ€ before, gates with a history of failure, or ships that returnedâ€¦ altered. â€¢ Crews trade stories, warnings, and unofficial maps wherever they dock. Information is often more valuable than money. Risk and Reward â€¢ Every run carries the risk of Corridor collapse, radiation overexposure, piracy, or mechanical failure. â€¢ But for many, a ship job is the only chance at movement, purpose, or upward mobility. â€¢ Veteran crews rarely retire. Most either vanish, get stuck planetside after a failed job, or become permanent fixtures in the darker corners of a colony bar.",
                        "updated":  1766132672,
                        "folder":  "Basic Lore",
                        "relativeWithin":  "Ships.md"
                    },
                    {
                        "relative":  "Basic Lore/Space Stations.md",
                        "title":  "Space Stations",
                        "excerpt":  "Space stations serve as larger, more developed variants of outposts, functional hubs positioned primarily in orbit or deep space, often near corridor gates. Unlike colonies, the...",
                        "search":  "Space stations serve as larger, more developed variants of outposts, functional hubs positioned primarily in orbit or deep space, often near corridor gates. Unlike colonies, they typically lack permanent civilian populations and instead operate with rotating crews of 12 to 25 workers, plus the transient presence of visiting ship crews. Their roles vary: some function as refueling or trade posts, others as military installations, research platforms, or regional relay points for logistics and communication. Ownership is usually centralized, with the core government overseeing most stations, though some may be administered by local colonies depending on their region and purpose. Their locations are strategically chosen, especially around corridor entries and exits, where they act as critical â€œfirst stopsâ€ for arriving vessels. Space stations are not self-sufficient. They rely heavily on external supply runs and consistent maintenance to remain operational, though with proper care they are built to endure for decades. Accessibility ranges from open ports to heavily restricted facilities depending on the stationâ€™s purpose. While life aboard a station is utilitarian and often monotonous, crews may include a mix of maintenance personnel, engineers, medical staff, shopkeepers, scientists, and security, reflecting the stationâ€™s specific needs.",
                        "updated":  1766132684,
                        "folder":  "Basic Lore",
                        "relativeWithin":  "Space Stations.md"
                    },
                    {
                        "relative":  "Basic Lore/Outposts.md",
                        "title":  "Outposts",
                        "excerpt":  "Outposts are small, often isolated installations that serve as utility points throughout human space. Unlike colonies, they are not intended for long-term habitation or large po...",
                        "search":  "Outposts are small, often isolated installations that serve as utility points throughout human space. Unlike colonies, they are not intended for long-term habitation or large populations. Most are staffed by fewer than a dozen personnel at any given time, if at all. Many outposts operate unmanned, visited only when ships dock to refuel, repair, or drop off rotating maintenance crews. Their functions vary widely: some monitor junction systems with multiple corridor links, others serve as rest stops, emergency shelters, or orbital watchpoints for military or survey activity. A few are embedded into asteroids for resource sampling or data relay. Outposts are typically built by nearby colonies or by central government agencies and powered by solar panels and battery systems. Supplies are delivered intermittently by ship, making them dependent on external support. While rarely intentionally abandoned, many outposts fall off the official registry once their purpose fades or routes shift, leaving them vulnerable to decay or reappropriation by scavengers and pirates. Most threats they face are environmental, systemic failures, radiation exposure, or natural hazards; but remote locations sometimes attract hostile attention. Life at an outpost, for those who live there, is routine shift work: lonely, quiet, and largely thankless.",
                        "updated":  1766132726,
                        "folder":  "Basic Lore",
                        "relativeWithin":  "Outposts.md"
                    },
                    {
                        "relative":  "Basic Lore/Colonies.md",
                        "title":  "Colonies",
                        "excerpt":  "Human colonies are scattered across dozens of star systems, founded during the peak of interstellar expansion when Corridors were considered stable and Gates were plentiful. The...",
                        "search":  "Human colonies are scattered across dozens of star systems, founded during the peak of interstellar expansion when Corridors were considered stable and Gates were plentiful. Their survival now depends heavily on whether their Corridor routes remain active. They generally sustain a population of anywhere between 50-250, but rarely more due to resource strain. Unfortunately; this means that almost no colony has the population size to sustainably reproduce on its own if left isolated. Structure and Environment â€¢ Colonies are almost always enclosed, industrial, and highly functional-prioritizing longevity and utility over comfort. â€¢ Most are built into hardened structures on planetary surfaces, inside asteroids, or within artificial stations. Windows are rare, aesthetics rarer. â€¢ Life is cramped and resource-regulated. Colonies rely on strict maintenance cycles, rationed supplies, and relentless work routines to stay viable. â€¢ Atmospheric and gravity systems vary; some use planetary conditions, others rely on artificial life support. Population and Culture â€¢ Most colonies are populated by a mix of laborers, engineers, security forces, and administrators. â€¢ Civilian life revolves around survival, utility work, and maintaining infrastructure. Entertainment and culture exist but are minimal and usually improvised. â€¢ Some colonies still express loyalty to Earth, while others have drifted into pragmatic isolation or outright de facto independence. â€¢ Colonists tend to be resilient, blunt, and practical, shaped by generations of hardship and self-reliance. Supply and Isolation â€¢ Colonies require supplies, information, and personnel from other systems to remain sustainable. â€¢ If a Corridor shifts or collapses, a colony can be cut off indefinitely, losing all contact with the wider network. Â Â Â Â â—¦ If the Corridor returns, it often does so too late. Many such colonies are found dead or nearly so. Â Â Â Â â—¦ Reclaimed colonies are sometimes resettled or salvaged, with remnants of the previous population still present-sometimes alive, usually not. Quarantine and Hazards â€¢ Disease, resource collapse, environmental breach, and structural decay are common risks. â€¢ Some colonies enact quarantine procedures during incidents, though enforcement varies. â€¢ Rumors of \"ghost colonies\" persist; places that went dark and were later found abandoned, their interiors intact, but with no sign of where the inhabitants went. Strategic Role â€¢ Colonies extract raw materials, grow food, generate energy, or manage relay infrastructure essential to human survival. â€¢ Each one is a node in a fraying web, propped up by ship crews and corridor routes that grow less reliable every year.",
                        "updated":  1766132844,
                        "folder":  "Basic Lore",
                        "relativeWithin":  "Colonies.md"
                    },
                    {
                        "relative":  "Basic Lore/Corridors.md",
                        "title":  "Corridors",
                        "excerpt":  "Corridors are naturally occurring interstellar pathways that allow faster-than-light travel between distant regions of the galaxy. Humanity did not create them, only discovered ...",
                        "search":  "Corridors are naturally occurring interstellar pathways that allow faster-than-light travel between distant regions of the galaxy. Humanity did not create them, only discovered and exploited them. Though the mechanics are not fully understood, ships entering a Corridor are able to traverse immense distances in a fraction of the time; usually days or weeks, compared to centuries by conventional means. Structure and Function â€¢ Corridors have two or more stable entry/exit regions (informally referred to as \"positions\" or \"points\"). â€¢ Travel through a Corridor is one of the only methods of practical interstellar transit. â€¢ Their interior is hostile, a voidlike medium saturated with Corridor Radiation, requiring hardened ships and constant maintenance. â€¢ Ships must exit through a gate; entry and exit without one is nearly suicidal, often resulting in catastrophic loss Gate Usage â€¢ Gates are massive human-built structures that anchor Corridors in place, forcing them open and stable for transit. â€¢ Without a gate, Corridors become inaccessible, unpredictable, or dangerous to enter. â€¢ Gates are resource-intensive, immobile, and require continual power and upkeep. â€¢ If a Corridor shifts or closes, a gate may become useless, requiring recovery and salvage or abandonment. Shifting and Collapse â€¢ Corridors naturally shift between a set of rough positions (usually 8â€“12). The shift is unpredictable, but known routes may return over time. â€¢ Even when a Corridor shifts back to a previous position, it never returns to the exact coordinates. Gates must be relocated within the system to match the new offset. â€¢ A collapse is different from a shift. When a Corridor collapses: Â Â Â Â â—¦ One of its former positions is permanently lost. Â Â Â Â â—¦ It either adds a new position to its rotation or becomes a new Corridor entirely, with different entry/exit points. Â Â Â Â â—¦ Collapsed Corridors no longer emit Corridor Radiation and cannot be reaccessed. Implications â€¢ Human expansion depended heavily on stable Corridors. As their reliability degraded, so did interstellar infrastructure. â€¢ Colonies stranded by shifting or collapsing Corridors often suffer total isolation, leading to slow decline or death. â€¢ Some Corridors still offer partial stability, allowing travel with heavy risk but remain the only option for keeping distant colonies alive.",
                        "updated":  1766132790,
                        "folder":  "Basic Lore",
                        "relativeWithin":  "Corridors.md"
                    },
                    {
                        "relative":  "Basic Lore/Gates.md",
                        "title":  "Gates",
                        "excerpt":  "Gates are colossal human-made megastructures designed to stabilize and hold open Corridors for reliable interstellar travel. Without them, Corridor entry and exit is either impo...",
                        "search":  "Gates are colossal human-made megastructures designed to stabilize and hold open Corridors for reliable interstellar travel. Without them, Corridor entry and exit is either impossible or catastrophically unsafe. Purpose and Function â€¢ Gates create a stable entry or exit point into a Corridor by anchoring it in place and supplying vast amounts of power to maintain the connection. â€¢ Without a gate, Corridors remain unusable for most vessels. Entry leads to uncontrolled, often fatal results. â€¢ Gates are located near colonies, stations, or key sectors and are crucial for maintaining transport, communication, and supply lines. Construction and Limitations â€¢ Building a gate is a massive logistical effort requiring specialized equipment, a stable orbit or staging point, and long-term maintenance infrastructure. â€¢ Once constructed, gates cannot be moved under their own power. However, they can be relocated short distances with auxiliary tug fleets if a Corridor shifts within the same system. â€¢ If a Corridor shifts out of range, the gate becomes effectively useless unless it later returns nearby. â€¢ Gates may be repaired and reactivated if a Corridor shifts back into a reachable area, but alignment is never exact and always requires re-positioning. Failure and Risk â€¢ If a gateâ€™s power fails or control systems destabilize, the Corridor may collapse or shift prematurely, posing catastrophic risk to ships in transit. â€¢ Older gates, especially those built during humanityâ€™s rapid expansion period, are more prone to malfunctions and radiation leakage. â€¢ Gates at dead routes (where Corridors have collapsed or shifted irreversibly) are often left to float abandoned, unusable but too expensive to dismantle. Decontamination â€¢ Operational gates include decontamination infrastructure for handling Corridor Radiation exposure: Â Â Â Â â—¦ Hull cleansing systems Â Â Â Â â—¦ Crew medical screening and quarantine zones Â Â Â Â â—¦ Radiation scrubbing for key components â€¢ Only ships passing through a gated exit receive full decontamination; those using natural or emergency exits risk spreading contamination or dying from exposure. Strategic Value â€¢ Gates are among the most valuable and contested infrastructure in human space. â€¢ Their control determines who lives, who starves, and who remains connected to the rest of humanity. â€¢ Many derelict or decaying colonies still maintain minimal personnel around gate structures, hoping for a Corridor to shift back into range.",
                        "updated":  1766132770,
                        "folder":  "Basic Lore",
                        "relativeWithin":  "Gates.md"
                    }
                ]
};
